#!/bin/bash

FRAMEWORK_NAME=FPPicker.framework
SRC_DIR=${TARGET_BUILD_DIR}/${FULL_PRODUCT_NAME}
DEST_DIR=${SRCROOT}/dist/${FULL_PRODUCT_NAME}

if [ -d $DEST_DIR ] && [ -d $SRC_DIR ];
then
  echo "Bundle $DEST_DIR exists, deleting."
  rm -Rf $DEST_DIR
fi

if [ -d $SRC_DIR ];
then
  echo "Copying into ${DEST_DIR}"
  cp -pR ${SRC_DIR} ${DEST_DIR}
fi
